services:
  db:
    image: postgres:14
    env_file: .env
    ports:
      - "5432:5432"
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env