# Generated by Django 5.2 on 2025-04-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plate',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
