# Generated by Django 5.2 on 2025-04-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_user_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plate',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
    ]
